### ISSUE TITLE
Smart Banner doesn't show 

### ISSUE THREAD

**Issue by jslok** [sbugert/react-native-admob#193] opened 2017-10-07 03:46 UTC
I tested on a fresh react-native project. All ad sizes display as expected except smart banners.

Using react-native-admob version beta.2 with react-native 0.49.1 on android. ios appears to work fine.

onAdLoaded does fire, but the ad spot is just blank with smart banners.

			  <AdMobBanner
				adSize="smartBannerPortrait"
				adUnitID="app-d"
				testDevices={[AdMobBanner.simulatorId]}
				onAdLoaded={() => this.setState({bannerDims:bannerDimsAd})}
				onAdFailedToLoad={() => this.setState({bannerDims:bannerDimsEmpty})}
				/>

**Comment by jslok** [comment] 2017-10-07 05:08
Forgot to say this is only an issue on android. ios appears to work fine with smart banners.

**Comment by koenpunt** [comment] 2017-10-07 10:15
I think there’s missing code here. Does the `setState` in `onAdLoaded` define the size of the container? Or what does it do?

**Comment by jslok** [comment] 2017-10-07 10:37
Yes it defines the size of the container. Banners show for all other ad sizes with the same code, just not for smart banners.

**Comment by jslok** [comment] 2017-10-07 10:39
I just tried without my onadloaded and experienced the same thing with a fresh rn install. All sizes work except smart banners. Are you able to reproduce or is it just me?

**Comment by nebmesemaou** [comment] 2017-10-09 13:44
same here

**Comment by rizzomichaelg** [comment] 2017-10-09 22:45
+1 here. other sizes work, but smart banners do not.

**Comment by rizzomichaelg** [comment] 2017-10-10 00:27
Looks like the problem is that in RNAdMobBannerViewManager.java this.adView.getAdSize() returns "412x50_as" after the ad has been loaded, so the compare with AdSize.SMART_BANNER fails.  The resulting width and height are then -1 and -2 which causes it to fail being displayed.

**Comment by jslok** [comment] 2017-10-10 02:08
@rizzomichaelg Thanks! That fix works for me.

**Comment by artemukolov** [comment] 2017-10-31 12:12
smartBannerLandscape and smartBannerPortrait still not working on android.

**Comment by jslok** [comment] 2017-11-01 04:28
@artemukolov the pr hasn't been merged yet. You can copy this file into your project until then and it will work.
https://github.com/rizzomichaelg/react-native-admob/blob/21b3dddcc7a5262debe00ff0faf70366b27a0688/android/src/main/java/com/sbugert/rnadmob/RNAdMobBannerViewManager.java

**Comment by artemukolov** [comment] 2017-11-01 06:16
oh, thanks a lot.

**Comment by koenpunt** [comment] 2017-11-12 21:04
This has been fixed on master, a release will follow shortly

**Closed by koenpunt** 2017-11-12 21:04 UTC
Labels: bug
