### ISSUE TITLE
Is this project still alive ?

### ISSUE THREAD

**Issue by Moverloia** [sbugert/react-native-admob#399] opened 2019-01-08 21:26 UTC
Hello, does anyone know is it safe to use this ?

Latest commit is 31 May 2018, soon it's going to be one year ago.

**Comment by SergiOnGit** [comment] 2019-01-09 18:56
Unfortunately it doesn't look alive. I'm using this plugin from April 2018 and i haven't seen any author answer here in issues

**Comment by koenpunt** [comment] 2019-01-09 21:53
As one of the maintainers I'm still using this library in production without issues.
I must add that I'm not using the latest version of RN in that project, so full compatibility is not guaranteed. Unfortunately I don't have the time to solve the issues I'm not having.
And also most issues on the repo are about people not being able to get there ads to show, which in 99% of the cases is because of incorrect AdMob configuration, and not because of this library not working.

**Comment by SergiOnGit** [comment] 2019-01-10 07:50
@koenpunt I agree 99% of issues are users fault :) with the latest RN it works fine, you only have to change android build.gradle configs.

**Comment by eathentica** [comment] 2019-01-10 23:34
I can confirm, that with the latest react-native 0.57.8 react-native-admob works perfectly. Everything I found here is enough. You do not need more information.

The only thing I have to change is the build.gradle file. I use SDK Version 27, and have to change the build.gradle as followed:

android {
    compileSdkVersion 27
    buildToolsVersion "27.0.3"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 26
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'com.facebook.react:react-native:+'
    implementation 'com.google.android.gms:play-services-ads:16.0.0'
}

But this really depends on your project-SDK. I also have to specify google play service to 16.0.0, because I use other google play services as well, which might not compatible with AdMob.

**Comment by hoboman313** [comment] 2019-01-13 09:33
@koenpunt there are some worthwhile improvements like #393 that require your attention

**Comment by univers3** [comment] 2019-02-04 09:58
@koenpunt: @hoboman313 is right!

**Comment by wkirby** [comment] 2019-02-17 06:36
@koenpunt I totally understand you can’t fix issues you don’t have in production, but there are a number of open PRs to address some of the real issues this library currently has. Is there any chance of having anything merged, or adding more maintainers who have the time to bring in updates?

**Comment by tmjordan** [comment] 2019-02-17 11:31
@wkirby try using RNFirebase, it is more stable and have other useful stuff. Of course it includes Admob.

**Comment by matamicen** [comment] 2019-02-27 21:23
@tmjordan RNFirebase includes Ad Manager? Can we use RNFirebase on RN in iOS also?

thanks.

**Comment by tmjordan** [comment] 2019-02-27 22:08
@matamicen yes it does and you can use it with rn on iOS and Android. It allows you to use all other firebase tool. I'm using it in my project

**Comment by matamicen** [comment] 2019-02-27 22:13
@tmjordan I didn't find clear information of how to use it, do you have some example of your project to share? it will be really appreciateed :) my email is matamicen@gmail.com 
Thanks a lot!!

**Comment by tmjordan** [comment] 2019-02-27 22:25
https://rnfirebase.io/docs/v5.x.x/installation/initial-setup
https://rnfirebase.io/docs/v5.x.x/admob/ios
https://rnfirebase.io/docs/v5.x.x/admob/reference/admob

**Comment by matamicen** [comment] 2019-02-27 22:30
thanks! @tmjordan

**Comment by matamicen** [comment] 2019-02-28 04:40
@tmjordan I followed those guides in order to get the Ads working on Android and it worked on AdMob Test Ads :)
it is not working in DFP (now Ad Manager) ... Have you ever tried calling a DFP Ad with this library (react-native-firebase) ? Thanks again.

**Comment by tmjordan** [comment] 2019-02-28 11:08
@matamicen sorry i don't use Ad Manager, so i can't help you. But i don't think that rnfirebase supports that. You can combine it with react-native-admob or other library

**Comment by matamicen** [comment] 2019-02-28 11:21
thanks! @tmjordan

**Comment by mdekrey** [comment] 2019-03-10 19:38
Considering the [Expo app supports this library via npm](https://docs.expo.io/versions/latest/sdk/admob/), I think it's important that this repo is kept up to date. That being said, I cannot wait for updates from the existing maintainers, and the react-native-firebase project seems to be going under significant changes.

I've started duplicating a few PRs and merging the original branches into the master on my fork at mdekrey/react-native-admob. I've included instructions on how to depend upon a specific commit of my branch via command line, and I'd be willing to accept PRs there, too, but so far I am tracking the PRs that I'm merging by linking them to corresponding PRs in this fork (and trying to accept as much from other contributors as possible!) 

I'm trying to be as transparent as I can in the work that goes on in a different repository, so it can be redone if this original fork gets active maintainers again.

**Comment by girishjjain** [comment] 2019-04-18 15:50
For all those confirming that this library still works for them, has anyone tried using Interstitial ads on Android? 

Banner works for me on both iOS and Android but Interstitials only work on iOS. I am using Expo SDK v32.

**Comment by koenpunt** [comment] 2019-04-18 21:11
I'm going to revise an app that's running in production using this library soon, so then I can probably also address at the issues people are having. Can't give a timeframe right now, but I'll post something here when I do progress.

**Comment by SergiOnGit** [comment] 2019-04-19 07:43
Just put this code in admob android build.gradle file and everything should work. I have tested it from RN v57.

```
apply plugin: 'com.android.library'

android {
    compileSdkVersion 27
    buildToolsVersion "27.0.3"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 26
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'com.facebook.react:react-native:+'
    implementation 'com.google.android.gms:play-services-ads:16.0.0'
}
```

**Comment by 123dma** [comment] 2019-08-20 15:06
@koenpunt have you feedback about this library in production ?

**Comment by koenpunt** [comment] 2019-08-20 15:31
> @koenpunt have you feedback about this library in production ?

I'm still using it in production without issues. But I recently started updating an app where I'm using it, so I might update the library while at it. But no promises.

**Comment by koenpunt** [comment] 2019-09-15 21:35
I've opened a PR to bring this library up to date with the latest version of React Native: #472

**Closed by koenpunt** 2019-09-15 21:35 UTC
