### ISSUE TITLE
Internal Error, an invalid response was received from the ad server.

### ISSUE THREAD

**Issue by hyorax** [sbugert/react-native-admob#250] opened 2018-01-26 11:55 UTC
Hi, 
This is an error when I add an ad.
![26962393_244742416065154_2562616130662639894_o](https://user-images.githubusercontent.com/25365040/35438792-f82f47c4-02a8-11e8-92f8-af58856f3bc0.jpg)

Pls help me.

**Comment by bvv218** [comment] 2018-01-27 20:07
[220](https://github.com/sbugert/react-native-admob/issues/220)

**Comment by hyorax** [comment] 2018-01-28 15:10
the problem continues.

**Comment by hyorax** [comment] 2018-01-29 11:56
please dissolve

**Comment by hyorax** [comment] 2018-02-02 15:16
I wait.

**Comment by koenpunt** [comment] 2018-02-03 12:50
Duplicate of #220

**Closed by koenpunt** 2018-02-03 12:50 UTC

**Comment by bhargav82** [comment] 2018-07-04 09:29
I had the same issue with my app. You just need to wait for a little. Your ad id is newly created so it will take some time to fetch ads from google servers. So give it some time and it will work soon. the first day I will try with my AdMob account its say "Internal error, an invalid response was received from the ad server." on next day try with run-android it's working fine for me. please wait for some time max 1 day after the create AdMob banner add after it's work.
