### ISSUE TITLE
The ad unit ID can only be set once on InterstitialAd

### ISSUE THREAD

**Issue by shaikhussian** [sbugert/react-native-admob#53] opened 2016-09-22 05:55 UTC
hai when i run react-native-admob in android  i am getting an error like this, I got this error like this
The ad unit ID can only be set once on interstitialAd
![screenshot_2016-09-22-11-05-36](https://cloud.githubusercontent.com/assets/11956308/18738194/160e1b64-80b7-11e6-92fb-55c1a2d04b77.png)
Any one please give me suggestions that how to resolve this error
**react-native version:**
"react-native": "^0.33.0"

**Comment by sumantimalsina9** [comment] 2016-09-22 10:42
i am also facing the same problem..

**Comment by sbugert** [comment] 2016-09-22 11:12
Can you show me your code?

Your probably doing what the error says – calling `setAdUnitId` twice.

**Comment by shaikhussian** [comment] 2016-09-22 12:17
when i am in screen of admob displaying and after some actions i moved to other screen and again if i came to the same admob  screen then only this error is showing only in android

**Comment by willoughby** [comment] 2016-09-22 13:23
I made a similar mistake by setting the id in component did mount,

**Comment by sumantimalsina9** [comment] 2016-09-22 13:33
@willoughby is your problem solved by removing these lines???

    AdMobInterstitial.setTestDeviceID('EMULATOR');
    AdMobInterstitial.setAdUnitID('ca-app-pub-3940256099942544/1033173712');

**Comment by sbugert** [comment] 2016-09-22 13:52
As @willoughby said, the problem is likely caused by setting the ad unit id in a lifecycle method.
The interstital module is a singleton, so you only set the id once. Try moving it outside of your component, i.e. right after importing the module.

**Comment by sumantimalsina9** [comment] 2016-09-22 14:17
i really cant figure it out.  
the app still crashes . I have removed the setAdUnitId in componentDidMount and added in


  <AdMobBanner
          bannerSize={this.state.bannerSize}
          testDeviceID="EMULATOR"
          adUnitID="ca-app-pub-3940256099942544/1033173712"
        />

**Comment by sumantimalsina9** [comment] 2016-09-22 15:14
thankyou for your quick response. You saved my day.

**Comment by sbugert** [comment] 2016-09-22 16:00
I'm happy to change the example if you tell me what you find confusing.

```javascript
AdMobInterstitial.setTestDeviceID('EMULATOR');
AdMobInterstitial.setAdUnitID('ca-app-pub-3940256099942544/1033173712');
```
should not be in `componentDidMount`, I will change that. In this case it works because the root component will only get mounted once.

**Closed** 2016-10-11 11:14 UTC
